#! /usr/bin/python

import subprocess as sub
import os
import argparse

parser = argparse.ArgumentParser()

parser.add_argument("-m", "--mirror", help = "Specify custom mirror, default is https://ftp.halifax.rwth-aachen.de/blender/release/")
parser.add_argument("-p", "--path", help = "Specify custom install path, default is ~/Apps/blender/")

args = parser.parse_args()

if args.mirror == None:
    mirror = "https://ftp.halifax.rwth-aachen.de/blender/release/"
elif args.mirror[:5] == "https":
    mirror = args.mirror
else:
    input("Enter a link and try again, ENTER to quit")
    quit()

if args.path:
    input(f"Installing at {args.path}, ENTER to continue")
    install_path = args.path
else:
    install_path = "~/Apps/blender/"

def run(cmd):
    try:
        return sub.check_output(cmd, shell=True, text=True).strip()
    except:
        if cmd.find("blender") != -1:
            return "0.0.0"
        else:
            input("Network error, ENTER to quit")
            quit()

cur_ver = run("blender -v | sed -n '1p' | grep -oP '[0-9].*'")
print("Installed version:", cur_ver)

dirs = run("curl --silent https://ftp.halifax.rwth-aachen.de/blender/release/ | grep -o 'href=\"Blender[0-9]\\.[0-9]' | grep -oP 'Ble.*'").split("\n")

for i in range(len(dirs)):
    files = run(f"curl --silent https://ftp.halifax.rwth-aachen.de/blender/release/{dirs[-(i+1)]}/ | grep -oP '\"blender-[0-9]\\.[0-9]\\.[0-9]'[^\\\"]+ | sed 's/\"//'").split("\n")
    if files == [''] or files == ['0.0.0']:
        continue
    else:
        latestdir = dirs[-(i+1)]
        break
#print(files)

newest = 0
for i in files:
    if int(i[12]) > newest:
        newest = int(i[12])
late_ver = f"{latestdir[7:11]}.{newest}"
print(f"Latest version: {late_ver}")

if late_ver != cur_ver:
    if input("Update available, install? [Y/n] ").lower() != "n":
        for i in files:
            if i[12] == str(newest) and i.find("linux") != -1 and i.find("x64") != -1:
                try:
                    os.system(f"curl -o /tmp/blender.tar.xz {mirror}{latestdir}/{i}")
                except:
                    input("Network error, ENTER to quit")
                    quit()
                os.system("tar -xf /tmp/blender.tar.xz -C /tmp")
                os.system(f"rm -rf {install_path}* && mv /tmp/{i[:-7]}/* {install_path}")
                input("Updated, ENTER to quit")
else:
    input("No updates, ENTER to quit")
    quit()
